using System.Diagnostics.CodeAnalysis;
using System.Runtime.Serialization;

namespace ProSoft.Library.Core.Exceptions;

/// <summary>
/// Class DatabaseEngineNotSupportedException.
/// Implements the <see cref="System.Exception" />
/// </summary>
/// <seealso cref="System.Exception" />
/// <autogeneratedoc />
[Serializable]
[ExcludeFromCodeCoverage]
public class DatabaseEngineNotSupportedException : Exception
{
    /// <summary>
    /// Initializes a new instance of the <see cref="DatabaseEngineNotSupportedException"/> class.
    /// </summary>
    /// <autogeneratedoc />
    public DatabaseEngineNotSupportedException()
    {
        
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DatabaseEngineNotSupportedException"/> class.
    /// </summary>
    /// <param name="message">The message that describes the error.</param>
    /// <autogeneratedoc />
    public DatabaseEngineNotSupportedException(string messsage) : base(messsage)
    {

    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DatabaseEngineNotSupportedException"/> class.
    /// </summary>
    /// <param name="message">The error message that explains the reason for the exception.</param>
    /// <param name="innerException">The exception that is the cause of the current exception, or a null reference (<see langword="Nothing" /> in Visual Basic) if no inner exception is specified.</param>
    /// <autogeneratedoc />
    public DatabaseEngineNotSupportedException(string message, Exception innerException) : base(message, innerException)
    {

    }
}
